spring.application.name=homework2
spring.data.mongodb.uri=mongodb+srv://tien100609:qVOS409gF5vgRTil@motbookdb.m8rl8li.mongodb.net/web2

# JWT cấu hình cơ bản (có thể đổi qua ENV)
app.jwt.secret=change-me-please-32bytes-secret-key
app.jwt.expiration-ms=86400000

# CORS: cho phép React dev server
app.cors.allowed-origins=http://localhost:3000
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=Authorization,Content-Type
app.cors.allow-credentials=true